### PR TITLE
Enabling higher DPI settings

### PR DESCRIPTION
**Pull request by mateusbs17**
- Using the right size to calculate the tile grid used to create the snapshot

### CODE REVIEW

**Comment by mateusbs17** [comment]
I am looking into the travis logs to see why it failed, but it looks like the test function relies on the older function `abaculus.tileList` and it had a miss calculation for scales != 1.

**Comment by mateusbs17** [comment]
Changing test case with an example from the real world and to reflect the new calculations.

The input is the same as the following snapshot URL parameters:
https://maps.wikimedia.org/img/osm-intl,5,-24.405,-47.368,250x250.png

The tile outputs are the following:
https://maps.wikimedia.org/osm-intl/5/11/17.png
https://maps.wikimedia.org/osm-intl/5/12/17.png
https://maps.wikimedia.org/osm-intl/5/11/18.png
https://maps.wikimedia.org/osm-intl/5/12/18.png

**Comment by mdholloway** [comment]
Makes sense (I think) and seems to work well.  I guess this is a bug upstream, too?

**Comment by mdholloway** [comment]
Incidentally, it looks like there's some kind of scale value rounding happening even with the fix.  According to sources.dev.yaml, the following scale values should be possible:

`[1.3, 1.5, 2, 2.6, 3]`

But 1.3 appears to be rounded down to 1x (no scaling), and 1.5, 2, 2.6, and 3 all result in an identical image (scaled to 2x in reality, I think).

**Comment by mateusbs17** [comment]
Yes, didn't realized that before. [Snapshot is truncating the scale](https://github.com/kartotherian/snapshot/blob/master/lib/snapshot.js#L122). Removing this line does make it work, but with some lack of precision. I will investigate and maybe update snapshots PR (this line must have a reason to exist).

> Makes sense (I think) and seems to work well. I guess this is a bug upstream, too?
Yes! Actually this repo is some commits behind. I will update and them make the PR to upstream.

**Comment by mateusbs17** [comment]
This bug can't be fixed without abaculus changing. We should discuss our strategy because this could be not the only situation where we need to upgrade our libraries to fix some issue.

**Comment by mateusbs17** [comment]
Closing. It was solved [here](https://github.com/kartotherian/abaculus/pull/2).

**Pull request closed without merging**
